name: Deploy Website via FTP

# Тригер: запускати екшен при кожному пуші в гілку main (або master)
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Копіюємо код репозиторію на віртуальну машину GitHub
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Потрібно для того, щоб екшен міг порівняти коміти і знайти лише змінені файли

    # 2. Завантажуємо файли на FTP
    - name: 🚀 Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /core2/prm # Якщо потрібно завантажити в конкретну папку на сервері, розкоментуйте цей рядок
